#! /bin/bash 

DOTENV="../portail/.envs"

if ! test -f $DOTENV; then
    echo "NO"
else
    echo "DOTENV EXISTS"
    if ! grep -q "DIAF" $DOTENV; then
        echo "DIAF DOESN'T EXISTS"
    else
        echo "DIAF EXISTS"
    fi
fi